version: '2'

services:
  postgres:
    image: postgres
    privileged: true
    env_file:
      - config.env
    environment:
      - PGDATA=/data/postgres
    volumes:
      - ${PG_DATA}:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    privileged: true
    env_file:
      - config.env
    volumes:
      - ${PGADMIN_DATA}:/root/.pgadmin
    ports:
      - "15432:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
